import { describe, it, expect } from "vitest";
import { formatCollection, formatLevel, parseCollection, parseLevel } from "../lib/level-format.js";
import { createGame, isSolved } from "../lib/sokoban.js";

const PICTURE = ["#######", "#@-$-.#", "#--*--#", "#######"];

describe("parseLevel", () => {
  it("reads the walls, the goals, the boxes and the keeper", () => {
    const level = parseLevel(PICTURE);
    expect(level.cols).toBe(7);
    expect(level.rows).toBe(4);
    expect(level.walls[0]).toBe(1);
    expect(level.walls[1 * 7 + 1]).toBe(0);
    expect(level.player).toBe(1 * 7 + 1);
    expect(level.boxes.sort((a, b) => a - b)).toEqual([1 * 7 + 3, 2 * 7 + 3]);
    expect(level.goals.sort((a, b) => a - b)).toEqual([1 * 7 + 5, 2 * 7 + 3]);
  });

  it("counts a box on a goal as both", () => {
    const level = parseLevel(["######", "#@*$.#", "######"]);
    expect(level.boxes.length).toBe(2);
    expect(level.goals.length).toBe(2);
  });

  it("counts a keeper on a goal as both", () => {
    const level = parseLevel(["#####", "#+$-#", "#####"]);
    expect(level.goals).toEqual([1 * 5 + 1]);
    expect(level.player).toBe(1 * 5 + 1);
  });

  it("refuses a picture with ragged rows", () => {
    expect(() => parseLevel(["####", "#@-#-", "####"])).toThrow(/wide/);
  });

  it("refuses an unknown glyph", () => {
    expect(() => parseLevel(["####", "#@x#", "####"])).toThrow(/unknown glyph/);
  });

  it("refuses a picture with no keeper or two of them", () => {
    expect(() => parseLevel(["####", "#-$#", "####"])).toThrow(/no keeper/);
    expect(() => parseLevel(["#####", "#@@#", "#####"])).toThrow(/wide|second keeper/);
    expect(() => parseLevel(["######", "#@-@-#", "######"])).toThrow(/second keeper/);
  });

  it("refuses a picture where the boxes and goals do not match", () => {
    expect(() => parseLevel(["######", "#@$--#", "######"])).toThrow(/boxes but/);
  });

  it("refuses an empty picture", () => {
    expect(() => parseLevel([])).toThrow(/no rows/);
    expect(() => parseLevel([""])).toThrow(/no columns/);
  });
});

describe("formatLevel", () => {
  it("draws back exactly what was read", () => {
    expect(formatLevel(parseLevel(PICTURE))).toEqual(PICTURE);
  });

  it("survives a round trip for every glyph", () => {
    const picture = ["######", "#+*$.#", "#-#$-#", "######"];
    expect(formatLevel(parseLevel(picture))).toEqual(picture);
  });
});

describe("parseCollection", () => {
  const text = [
    "; a collection",
    "; second comment",
    "",
    "#####",
    "#@$.#",
    "#####",
    "",
    "######",
    "#@$-.#",
    "######",
    "",
  ].join("\n");

  it("reads every level between the blank lines", () => {
    const levels = parseCollection(text);
    expect(levels.length).toBe(2);
    expect(levels[0].cols).toBe(5);
    expect(levels[1].cols).toBe(6);
  });

  it("ignores comments and trailing blank lines", () => {
    expect(parseCollection("; only a comment\n\n\n")).toEqual([]);
  });

  it("copes with carriage returns", () => {
    const levels = parseCollection("#####\r\n#@$.#\r\n#####\r\n");
    expect(levels.length).toBe(1);
    expect(levels[0].cols).toBe(5);
  });

  it("reads a level that is not followed by a blank line", () => {
    expect(parseCollection("#####\n#@$.#\n#####").length).toBe(1);
  });
});

describe("formatCollection", () => {
  it("writes a file that reads back as the same levels", () => {
    const levels = [parseLevel(PICTURE), parseLevel(["#####", "#@$.#", "#####"])];
    const text = formatCollection(levels, ["generated by a test"]);
    const back = parseCollection(text);
    expect(back.length).toBe(2);
    expect(formatLevel(back[0])).toEqual(formatLevel(levels[0]));
    expect(formatLevel(back[1])).toEqual(formatLevel(levels[1]));
  });

  it("puts the comments at the top", () => {
    const text = formatCollection([parseLevel(["#####", "#@$.#", "#####"])], ["hello"]);
    expect(text.split("\n")[0]).toBe("; hello");
  });

  it("writes no comment block when there is nothing to say", () => {
    const text = formatCollection([parseLevel(["#####", "#@$.#", "#####"])]);
    expect(text.charAt(0)).toBe("#");
  });

  it("never writes a line with trailing whitespace the hooks would eat", () => {
    const text = formatCollection([parseLevel(PICTURE)], ["note"]);
    for (const line of text.split("\n")) {
      expect(line).toBe(line.replace(/\s+$/, ""));
    }
  });
});

describe("a parsed level", () => {
  it("is a level the rule set can play", () => {
    const level = parseLevel(["#####", "#@$.#", "#####"]);
    const game = createGame(level);
    expect(isSolved(game)).toBe(false);
    expect(game.goals.length).toBe(1);
  });
});
