// A small seedable random number generator.
//
// `Math.random` cannot be seeded, and both the tests and the offline collection
// builder need to be able to produce the very same warehouse twice - the tests
// so a failure can be reproduced, the builder so the shipped collection is a
// function of its seed and can be regenerated byte for byte.
//
// mulberry32: 32 bits of state, good enough for scattering crates around a
// warehouse and short enough to read.
export function seeded(seed) {
  let state = seed >>> 0;
  return function random() {
    state = (state + 0x6d2b79f5) >>> 0;
    let t = state;
    t = Math.imul(t ^ (t >>> 15), t | 1);
    t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
